/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateModuleCpp.js
 */

#include "RTNLibOTAJSI.h"

namespace facebook::react {

static jsi::Value __hostFunction_NativeLibOTAModuleCxxSpecJSI_getProtocolConfig(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
  return static_cast<NativeLibOTAModuleCxxSpecJSI *>(&turboModule)->getProtocolConfig(
    rt
  );
}
static jsi::Value __hostFunction_NativeLibOTAModuleCxxSpecJSI_computeChunkSize(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
  return static_cast<NativeLibOTAModuleCxxSpecJSI *>(&turboModule)->computeChunkSize(
    rt,
    count <= 0 ? throw jsi::JSError(rt, "Expected argument in position 0 to be passed") : args[0].asNumber()
  );
}
static jsi::Value __hostFunction_NativeLibOTAModuleCxxSpecJSI_beginSession(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
  return static_cast<NativeLibOTAModuleCxxSpecJSI *>(&turboModule)->beginSession(
    rt,
    count <= 0 ? throw jsi::JSError(rt, "Expected argument in position 0 to be passed") : args[0].asString(rt),
    count <= 1 ? throw jsi::JSError(rt, "Expected argument in position 1 to be passed") : args[1].asString(rt),
    count <= 2 ? throw jsi::JSError(rt, "Expected argument in position 2 to be passed") : args[2].asNumber()
  );
}
static jsi::Value __hostFunction_NativeLibOTAModuleCxxSpecJSI_updateMtu(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
  return static_cast<NativeLibOTAModuleCxxSpecJSI *>(&turboModule)->updateMtu(
    rt,
    count <= 0 ? throw jsi::JSError(rt, "Expected argument in position 0 to be passed") : args[0].asNumber()
  );
}
static jsi::Value __hostFunction_NativeLibOTAModuleCxxSpecJSI_buildStartCommand(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
  return static_cast<NativeLibOTAModuleCxxSpecJSI *>(&turboModule)->buildStartCommand(
    rt
  );
}
static jsi::Value __hostFunction_NativeLibOTAModuleCxxSpecJSI_buildFinishCommand(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
  return static_cast<NativeLibOTAModuleCxxSpecJSI *>(&turboModule)->buildFinishCommand(
    rt
  );
}
static jsi::Value __hostFunction_NativeLibOTAModuleCxxSpecJSI_nextChunk(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
  return static_cast<NativeLibOTAModuleCxxSpecJSI *>(&turboModule)->nextChunk(
    rt
  );
}
static jsi::Value __hostFunction_NativeLibOTAModuleCxxSpecJSI_confirmChunkWritten(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
  return static_cast<NativeLibOTAModuleCxxSpecJSI *>(&turboModule)->confirmChunkWritten(
    rt,
    count <= 0 ? throw jsi::JSError(rt, "Expected argument in position 0 to be passed") : args[0].asNumber()
  );
}
static jsi::Value __hostFunction_NativeLibOTAModuleCxxSpecJSI_rewindToStart(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
  return static_cast<NativeLibOTAModuleCxxSpecJSI *>(&turboModule)->rewindToStart(
    rt
  );
}
static jsi::Value __hostFunction_NativeLibOTAModuleCxxSpecJSI_parseStatus(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
  return static_cast<NativeLibOTAModuleCxxSpecJSI *>(&turboModule)->parseStatus(
    rt,
    count <= 0 ? throw jsi::JSError(rt, "Expected argument in position 0 to be passed") : args[0].asString(rt)
  );
}
static jsi::Value __hostFunction_NativeLibOTAModuleCxxSpecJSI_applyStatus(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
  return static_cast<NativeLibOTAModuleCxxSpecJSI *>(&turboModule)->applyStatus(
    rt,
    count <= 0 ? throw jsi::JSError(rt, "Expected argument in position 0 to be passed") : args[0].asString(rt)
  );
}
static jsi::Value __hostFunction_NativeLibOTAModuleCxxSpecJSI_getProgress(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
  return static_cast<NativeLibOTAModuleCxxSpecJSI *>(&turboModule)->getProgress(
    rt
  );
}
static jsi::Value __hostFunction_NativeLibOTAModuleCxxSpecJSI_isTransferComplete(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
  return static_cast<NativeLibOTAModuleCxxSpecJSI *>(&turboModule)->isTransferComplete(
    rt
  );
}
static jsi::Value __hostFunction_NativeLibOTAModuleCxxSpecJSI_isFlashConfirmed(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
  return static_cast<NativeLibOTAModuleCxxSpecJSI *>(&turboModule)->isFlashConfirmed(
    rt
  );
}
static jsi::Value __hostFunction_NativeLibOTAModuleCxxSpecJSI_abortSession(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
  static_cast<NativeLibOTAModuleCxxSpecJSI *>(&turboModule)->abortSession(
    rt
  );
  return jsi::Value::undefined();
}

NativeLibOTAModuleCxxSpecJSI::NativeLibOTAModuleCxxSpecJSI(std::shared_ptr<CallInvoker> jsInvoker)
  : TurboModule("NativeLibOTAModule", jsInvoker) {
  methodMap_["getProtocolConfig"] = MethodMetadata {0, __hostFunction_NativeLibOTAModuleCxxSpecJSI_getProtocolConfig};
  methodMap_["computeChunkSize"] = MethodMetadata {1, __hostFunction_NativeLibOTAModuleCxxSpecJSI_computeChunkSize};
  methodMap_["beginSession"] = MethodMetadata {3, __hostFunction_NativeLibOTAModuleCxxSpecJSI_beginSession};
  methodMap_["updateMtu"] = MethodMetadata {1, __hostFunction_NativeLibOTAModuleCxxSpecJSI_updateMtu};
  methodMap_["buildStartCommand"] = MethodMetadata {0, __hostFunction_NativeLibOTAModuleCxxSpecJSI_buildStartCommand};
  methodMap_["buildFinishCommand"] = MethodMetadata {0, __hostFunction_NativeLibOTAModuleCxxSpecJSI_buildFinishCommand};
  methodMap_["nextChunk"] = MethodMetadata {0, __hostFunction_NativeLibOTAModuleCxxSpecJSI_nextChunk};
  methodMap_["confirmChunkWritten"] = MethodMetadata {1, __hostFunction_NativeLibOTAModuleCxxSpecJSI_confirmChunkWritten};
  methodMap_["rewindToStart"] = MethodMetadata {0, __hostFunction_NativeLibOTAModuleCxxSpecJSI_rewindToStart};
  methodMap_["parseStatus"] = MethodMetadata {1, __hostFunction_NativeLibOTAModuleCxxSpecJSI_parseStatus};
  methodMap_["applyStatus"] = MethodMetadata {1, __hostFunction_NativeLibOTAModuleCxxSpecJSI_applyStatus};
  methodMap_["getProgress"] = MethodMetadata {0, __hostFunction_NativeLibOTAModuleCxxSpecJSI_getProgress};
  methodMap_["isTransferComplete"] = MethodMetadata {0, __hostFunction_NativeLibOTAModuleCxxSpecJSI_isTransferComplete};
  methodMap_["isFlashConfirmed"] = MethodMetadata {0, __hostFunction_NativeLibOTAModuleCxxSpecJSI_isFlashConfirmed};
  methodMap_["abortSession"] = MethodMetadata {0, __hostFunction_NativeLibOTAModuleCxxSpecJSI_abortSession};
}


} // namespace facebook::react
