/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateModuleH.js
 */

#pragma once

#include <ReactCommon/TurboModule.h>
#include <react/bridging/Bridging.h>

namespace facebook::react {


  
#pragma mark - NativeLibOTAModuleOtaDataChunk

template <typename P0, typename P1, typename P2, typename P3, typename P4>
struct NativeLibOTAModuleOtaDataChunk {
  P0 payloadBase64;
  P1 offset;
  P2 length;
  P3 isLast;
  P4 hasData;
  bool operator==(const NativeLibOTAModuleOtaDataChunk &other) const {
    return payloadBase64 == other.payloadBase64 && offset == other.offset && length == other.length && isLast == other.isLast && hasData == other.hasData;
  }
};

template <typename T>
struct NativeLibOTAModuleOtaDataChunkBridging {
  static T types;

  static T fromJs(
      jsi::Runtime &rt,
      const jsi::Object &value,
      const std::shared_ptr<CallInvoker> &jsInvoker) {
    T result{
      bridging::fromJs<decltype(types.payloadBase64)>(rt, value.getProperty(rt, "payloadBase64"), jsInvoker),
      bridging::fromJs<decltype(types.offset)>(rt, value.getProperty(rt, "offset"), jsInvoker),
      bridging::fromJs<decltype(types.length)>(rt, value.getProperty(rt, "length"), jsInvoker),
      bridging::fromJs<decltype(types.isLast)>(rt, value.getProperty(rt, "isLast"), jsInvoker),
      bridging::fromJs<decltype(types.hasData)>(rt, value.getProperty(rt, "hasData"), jsInvoker)};
    return result;
  }

#ifdef DEBUG
  static jsi::String payloadBase64ToJs(jsi::Runtime &rt, decltype(types.payloadBase64) value) {
    return bridging::toJs(rt, value);
  }

  static double offsetToJs(jsi::Runtime &rt, decltype(types.offset) value) {
    return bridging::toJs(rt, value);
  }

  static double lengthToJs(jsi::Runtime &rt, decltype(types.length) value) {
    return bridging::toJs(rt, value);
  }

  static bool isLastToJs(jsi::Runtime &rt, decltype(types.isLast) value) {
    return bridging::toJs(rt, value);
  }

  static bool hasDataToJs(jsi::Runtime &rt, decltype(types.hasData) value) {
    return bridging::toJs(rt, value);
  }
#endif

  static jsi::Object toJs(
      jsi::Runtime &rt,
      const T &value,
      const std::shared_ptr<CallInvoker> &jsInvoker) {
    auto result = facebook::jsi::Object(rt);
    result.setProperty(rt, "payloadBase64", bridging::toJs(rt, value.payloadBase64, jsInvoker));
    result.setProperty(rt, "offset", bridging::toJs(rt, value.offset, jsInvoker));
    result.setProperty(rt, "length", bridging::toJs(rt, value.length, jsInvoker));
    result.setProperty(rt, "isLast", bridging::toJs(rt, value.isLast, jsInvoker));
    result.setProperty(rt, "hasData", bridging::toJs(rt, value.hasData, jsInvoker));
    return result;
  }
};



#pragma mark - NativeLibOTAModuleOtaProgress

template <typename P0, typename P1, typename P2, typename P3, typename P4>
struct NativeLibOTAModuleOtaProgress {
  P0 phase;
  P1 bytesSent;
  P2 bytesConfirmed;
  P3 totalBytes;
  P4 percent;
  bool operator==(const NativeLibOTAModuleOtaProgress &other) const {
    return phase == other.phase && bytesSent == other.bytesSent && bytesConfirmed == other.bytesConfirmed && totalBytes == other.totalBytes && percent == other.percent;
  }
};

template <typename T>
struct NativeLibOTAModuleOtaProgressBridging {
  static T types;

  static T fromJs(
      jsi::Runtime &rt,
      const jsi::Object &value,
      const std::shared_ptr<CallInvoker> &jsInvoker) {
    T result{
      bridging::fromJs<decltype(types.phase)>(rt, value.getProperty(rt, "phase"), jsInvoker),
      bridging::fromJs<decltype(types.bytesSent)>(rt, value.getProperty(rt, "bytesSent"), jsInvoker),
      bridging::fromJs<decltype(types.bytesConfirmed)>(rt, value.getProperty(rt, "bytesConfirmed"), jsInvoker),
      bridging::fromJs<decltype(types.totalBytes)>(rt, value.getProperty(rt, "totalBytes"), jsInvoker),
      bridging::fromJs<decltype(types.percent)>(rt, value.getProperty(rt, "percent"), jsInvoker)};
    return result;
  }

#ifdef DEBUG
  static jsi::String phaseToJs(jsi::Runtime &rt, decltype(types.phase) value) {
    return bridging::toJs(rt, value);
  }

  static double bytesSentToJs(jsi::Runtime &rt, decltype(types.bytesSent) value) {
    return bridging::toJs(rt, value);
  }

  static double bytesConfirmedToJs(jsi::Runtime &rt, decltype(types.bytesConfirmed) value) {
    return bridging::toJs(rt, value);
  }

  static double totalBytesToJs(jsi::Runtime &rt, decltype(types.totalBytes) value) {
    return bridging::toJs(rt, value);
  }

  static double percentToJs(jsi::Runtime &rt, decltype(types.percent) value) {
    return bridging::toJs(rt, value);
  }
#endif

  static jsi::Object toJs(
      jsi::Runtime &rt,
      const T &value,
      const std::shared_ptr<CallInvoker> &jsInvoker) {
    auto result = facebook::jsi::Object(rt);
    result.setProperty(rt, "phase", bridging::toJs(rt, value.phase, jsInvoker));
    result.setProperty(rt, "bytesSent", bridging::toJs(rt, value.bytesSent, jsInvoker));
    result.setProperty(rt, "bytesConfirmed", bridging::toJs(rt, value.bytesConfirmed, jsInvoker));
    result.setProperty(rt, "totalBytes", bridging::toJs(rt, value.totalBytes, jsInvoker));
    result.setProperty(rt, "percent", bridging::toJs(rt, value.percent, jsInvoker));
    return result;
  }
};



#pragma mark - NativeLibOTAModuleOtaProtocolConfig

template <typename P0, typename P1, typename P2, typename P3, typename P4, typename P5, typename P6, typename P7, typename P8, typename P9, typename P10, typename P11, typename P12, typename P13>
struct NativeLibOTAModuleOtaProtocolConfig {
  P0 deviceName;
  P1 controlCharUuid;
  P2 dataCharUuid;
  P3 statusCharUuid;
  P4 firmwareRevisionCharUuid;
  P5 versionLength;
  P6 cmdStart;
  P7 cmdFinish;
  P8 statusReady;
  P9 statusProgress;
  P10 statusError;
  P11 statusFinished;
  P12 minChunkSize;
  P13 maxChunkSize;
  bool operator==(const NativeLibOTAModuleOtaProtocolConfig &other) const {
    return deviceName == other.deviceName && controlCharUuid == other.controlCharUuid && dataCharUuid == other.dataCharUuid && statusCharUuid == other.statusCharUuid && firmwareRevisionCharUuid == other.firmwareRevisionCharUuid && versionLength == other.versionLength && cmdStart == other.cmdStart && cmdFinish == other.cmdFinish && statusReady == other.statusReady && statusProgress == other.statusProgress && statusError == other.statusError && statusFinished == other.statusFinished && minChunkSize == other.minChunkSize && maxChunkSize == other.maxChunkSize;
  }
};

template <typename T>
struct NativeLibOTAModuleOtaProtocolConfigBridging {
  static T types;

  static T fromJs(
      jsi::Runtime &rt,
      const jsi::Object &value,
      const std::shared_ptr<CallInvoker> &jsInvoker) {
    T result{
      bridging::fromJs<decltype(types.deviceName)>(rt, value.getProperty(rt, "deviceName"), jsInvoker),
      bridging::fromJs<decltype(types.controlCharUuid)>(rt, value.getProperty(rt, "controlCharUuid"), jsInvoker),
      bridging::fromJs<decltype(types.dataCharUuid)>(rt, value.getProperty(rt, "dataCharUuid"), jsInvoker),
      bridging::fromJs<decltype(types.statusCharUuid)>(rt, value.getProperty(rt, "statusCharUuid"), jsInvoker),
      bridging::fromJs<decltype(types.firmwareRevisionCharUuid)>(rt, value.getProperty(rt, "firmwareRevisionCharUuid"), jsInvoker),
      bridging::fromJs<decltype(types.versionLength)>(rt, value.getProperty(rt, "versionLength"), jsInvoker),
      bridging::fromJs<decltype(types.cmdStart)>(rt, value.getProperty(rt, "cmdStart"), jsInvoker),
      bridging::fromJs<decltype(types.cmdFinish)>(rt, value.getProperty(rt, "cmdFinish"), jsInvoker),
      bridging::fromJs<decltype(types.statusReady)>(rt, value.getProperty(rt, "statusReady"), jsInvoker),
      bridging::fromJs<decltype(types.statusProgress)>(rt, value.getProperty(rt, "statusProgress"), jsInvoker),
      bridging::fromJs<decltype(types.statusError)>(rt, value.getProperty(rt, "statusError"), jsInvoker),
      bridging::fromJs<decltype(types.statusFinished)>(rt, value.getProperty(rt, "statusFinished"), jsInvoker),
      bridging::fromJs<decltype(types.minChunkSize)>(rt, value.getProperty(rt, "minChunkSize"), jsInvoker),
      bridging::fromJs<decltype(types.maxChunkSize)>(rt, value.getProperty(rt, "maxChunkSize"), jsInvoker)};
    return result;
  }

#ifdef DEBUG
  static jsi::String deviceNameToJs(jsi::Runtime &rt, decltype(types.deviceName) value) {
    return bridging::toJs(rt, value);
  }

  static jsi::String controlCharUuidToJs(jsi::Runtime &rt, decltype(types.controlCharUuid) value) {
    return bridging::toJs(rt, value);
  }

  static jsi::String dataCharUuidToJs(jsi::Runtime &rt, decltype(types.dataCharUuid) value) {
    return bridging::toJs(rt, value);
  }

  static jsi::String statusCharUuidToJs(jsi::Runtime &rt, decltype(types.statusCharUuid) value) {
    return bridging::toJs(rt, value);
  }

  static jsi::String firmwareRevisionCharUuidToJs(jsi::Runtime &rt, decltype(types.firmwareRevisionCharUuid) value) {
    return bridging::toJs(rt, value);
  }

  static double versionLengthToJs(jsi::Runtime &rt, decltype(types.versionLength) value) {
    return bridging::toJs(rt, value);
  }

  static double cmdStartToJs(jsi::Runtime &rt, decltype(types.cmdStart) value) {
    return bridging::toJs(rt, value);
  }

  static double cmdFinishToJs(jsi::Runtime &rt, decltype(types.cmdFinish) value) {
    return bridging::toJs(rt, value);
  }

  static double statusReadyToJs(jsi::Runtime &rt, decltype(types.statusReady) value) {
    return bridging::toJs(rt, value);
  }

  static double statusProgressToJs(jsi::Runtime &rt, decltype(types.statusProgress) value) {
    return bridging::toJs(rt, value);
  }

  static double statusErrorToJs(jsi::Runtime &rt, decltype(types.statusError) value) {
    return bridging::toJs(rt, value);
  }

  static double statusFinishedToJs(jsi::Runtime &rt, decltype(types.statusFinished) value) {
    return bridging::toJs(rt, value);
  }

  static double minChunkSizeToJs(jsi::Runtime &rt, decltype(types.minChunkSize) value) {
    return bridging::toJs(rt, value);
  }

  static double maxChunkSizeToJs(jsi::Runtime &rt, decltype(types.maxChunkSize) value) {
    return bridging::toJs(rt, value);
  }
#endif

  static jsi::Object toJs(
      jsi::Runtime &rt,
      const T &value,
      const std::shared_ptr<CallInvoker> &jsInvoker) {
    auto result = facebook::jsi::Object(rt);
    result.setProperty(rt, "deviceName", bridging::toJs(rt, value.deviceName, jsInvoker));
    result.setProperty(rt, "controlCharUuid", bridging::toJs(rt, value.controlCharUuid, jsInvoker));
    result.setProperty(rt, "dataCharUuid", bridging::toJs(rt, value.dataCharUuid, jsInvoker));
    result.setProperty(rt, "statusCharUuid", bridging::toJs(rt, value.statusCharUuid, jsInvoker));
    result.setProperty(rt, "firmwareRevisionCharUuid", bridging::toJs(rt, value.firmwareRevisionCharUuid, jsInvoker));
    result.setProperty(rt, "versionLength", bridging::toJs(rt, value.versionLength, jsInvoker));
    result.setProperty(rt, "cmdStart", bridging::toJs(rt, value.cmdStart, jsInvoker));
    result.setProperty(rt, "cmdFinish", bridging::toJs(rt, value.cmdFinish, jsInvoker));
    result.setProperty(rt, "statusReady", bridging::toJs(rt, value.statusReady, jsInvoker));
    result.setProperty(rt, "statusProgress", bridging::toJs(rt, value.statusProgress, jsInvoker));
    result.setProperty(rt, "statusError", bridging::toJs(rt, value.statusError, jsInvoker));
    result.setProperty(rt, "statusFinished", bridging::toJs(rt, value.statusFinished, jsInvoker));
    result.setProperty(rt, "minChunkSize", bridging::toJs(rt, value.minChunkSize, jsInvoker));
    result.setProperty(rt, "maxChunkSize", bridging::toJs(rt, value.maxChunkSize, jsInvoker));
    return result;
  }
};



#pragma mark - NativeLibOTAModuleOtaSessionInfo

template <typename P0, typename P1, typename P2>
struct NativeLibOTAModuleOtaSessionInfo {
  P0 totalBytes;
  P1 chunkSize;
  P2 totalChunks;
  bool operator==(const NativeLibOTAModuleOtaSessionInfo &other) const {
    return totalBytes == other.totalBytes && chunkSize == other.chunkSize && totalChunks == other.totalChunks;
  }
};

template <typename T>
struct NativeLibOTAModuleOtaSessionInfoBridging {
  static T types;

  static T fromJs(
      jsi::Runtime &rt,
      const jsi::Object &value,
      const std::shared_ptr<CallInvoker> &jsInvoker) {
    T result{
      bridging::fromJs<decltype(types.totalBytes)>(rt, value.getProperty(rt, "totalBytes"), jsInvoker),
      bridging::fromJs<decltype(types.chunkSize)>(rt, value.getProperty(rt, "chunkSize"), jsInvoker),
      bridging::fromJs<decltype(types.totalChunks)>(rt, value.getProperty(rt, "totalChunks"), jsInvoker)};
    return result;
  }

#ifdef DEBUG
  static double totalBytesToJs(jsi::Runtime &rt, decltype(types.totalBytes) value) {
    return bridging::toJs(rt, value);
  }

  static double chunkSizeToJs(jsi::Runtime &rt, decltype(types.chunkSize) value) {
    return bridging::toJs(rt, value);
  }

  static double totalChunksToJs(jsi::Runtime &rt, decltype(types.totalChunks) value) {
    return bridging::toJs(rt, value);
  }
#endif

  static jsi::Object toJs(
      jsi::Runtime &rt,
      const T &value,
      const std::shared_ptr<CallInvoker> &jsInvoker) {
    auto result = facebook::jsi::Object(rt);
    result.setProperty(rt, "totalBytes", bridging::toJs(rt, value.totalBytes, jsInvoker));
    result.setProperty(rt, "chunkSize", bridging::toJs(rt, value.chunkSize, jsInvoker));
    result.setProperty(rt, "totalChunks", bridging::toJs(rt, value.totalChunks, jsInvoker));
    return result;
  }
};



#pragma mark - NativeLibOTAModuleOtaStatusEvent

template <typename P0, typename P1, typename P2, typename P3>
struct NativeLibOTAModuleOtaStatusEvent {
  P0 kind;
  P1 rawStatus;
  P2 errorCode;
  P3 bytesWritten;
  bool operator==(const NativeLibOTAModuleOtaStatusEvent &other) const {
    return kind == other.kind && rawStatus == other.rawStatus && errorCode == other.errorCode && bytesWritten == other.bytesWritten;
  }
};

template <typename T>
struct NativeLibOTAModuleOtaStatusEventBridging {
  static T types;

  static T fromJs(
      jsi::Runtime &rt,
      const jsi::Object &value,
      const std::shared_ptr<CallInvoker> &jsInvoker) {
    T result{
      bridging::fromJs<decltype(types.kind)>(rt, value.getProperty(rt, "kind"), jsInvoker),
      bridging::fromJs<decltype(types.rawStatus)>(rt, value.getProperty(rt, "rawStatus"), jsInvoker),
      bridging::fromJs<decltype(types.errorCode)>(rt, value.getProperty(rt, "errorCode"), jsInvoker),
      bridging::fromJs<decltype(types.bytesWritten)>(rt, value.getProperty(rt, "bytesWritten"), jsInvoker)};
    return result;
  }

#ifdef DEBUG
  static jsi::String kindToJs(jsi::Runtime &rt, decltype(types.kind) value) {
    return bridging::toJs(rt, value);
  }

  static double rawStatusToJs(jsi::Runtime &rt, decltype(types.rawStatus) value) {
    return bridging::toJs(rt, value);
  }

  static double errorCodeToJs(jsi::Runtime &rt, decltype(types.errorCode) value) {
    return bridging::toJs(rt, value);
  }

  static double bytesWrittenToJs(jsi::Runtime &rt, decltype(types.bytesWritten) value) {
    return bridging::toJs(rt, value);
  }
#endif

  static jsi::Object toJs(
      jsi::Runtime &rt,
      const T &value,
      const std::shared_ptr<CallInvoker> &jsInvoker) {
    auto result = facebook::jsi::Object(rt);
    result.setProperty(rt, "kind", bridging::toJs(rt, value.kind, jsInvoker));
    result.setProperty(rt, "rawStatus", bridging::toJs(rt, value.rawStatus, jsInvoker));
    result.setProperty(rt, "errorCode", bridging::toJs(rt, value.errorCode, jsInvoker));
    result.setProperty(rt, "bytesWritten", bridging::toJs(rt, value.bytesWritten, jsInvoker));
    return result;
  }
};

class JSI_EXPORT NativeLibOTAModuleCxxSpecJSI : public TurboModule {
protected:
  NativeLibOTAModuleCxxSpecJSI(std::shared_ptr<CallInvoker> jsInvoker);

public:
  virtual jsi::Object getProtocolConfig(jsi::Runtime &rt) = 0;
  virtual double computeChunkSize(jsi::Runtime &rt, double mtuSize) = 0;
  virtual jsi::Object beginSession(jsi::Runtime &rt, jsi::String firmwarePath, jsi::String version, double mtuSize) = 0;
  virtual double updateMtu(jsi::Runtime &rt, double mtuSize) = 0;
  virtual jsi::String buildStartCommand(jsi::Runtime &rt) = 0;
  virtual jsi::String buildFinishCommand(jsi::Runtime &rt) = 0;
  virtual jsi::Object nextChunk(jsi::Runtime &rt) = 0;
  virtual jsi::Object confirmChunkWritten(jsi::Runtime &rt, double byteLength) = 0;
  virtual jsi::Object rewindToStart(jsi::Runtime &rt) = 0;
  virtual jsi::Object parseStatus(jsi::Runtime &rt, jsi::String statusBase64) = 0;
  virtual jsi::Object applyStatus(jsi::Runtime &rt, jsi::String statusBase64) = 0;
  virtual jsi::Object getProgress(jsi::Runtime &rt) = 0;
  virtual bool isTransferComplete(jsi::Runtime &rt) = 0;
  virtual bool isFlashConfirmed(jsi::Runtime &rt) = 0;
  virtual void abortSession(jsi::Runtime &rt) = 0;

};

template <typename T>
class JSI_EXPORT NativeLibOTAModuleCxxSpec : public TurboModule {
public:
  jsi::Value create(jsi::Runtime &rt, const jsi::PropNameID &propName) override {
    return delegate_.create(rt, propName);
  }

  std::vector<jsi::PropNameID> getPropertyNames(jsi::Runtime& runtime) override {
    return delegate_.getPropertyNames(runtime);
  }

  static constexpr std::string_view kModuleName = "NativeLibOTAModule";

protected:
  NativeLibOTAModuleCxxSpec(std::shared_ptr<CallInvoker> jsInvoker)
    : TurboModule(std::string{NativeLibOTAModuleCxxSpec::kModuleName}, jsInvoker),
      delegate_(reinterpret_cast<T*>(this), jsInvoker) {}


private:
  class Delegate : public NativeLibOTAModuleCxxSpecJSI {
  public:
    Delegate(T *instance, std::shared_ptr<CallInvoker> jsInvoker) :
      NativeLibOTAModuleCxxSpecJSI(std::move(jsInvoker)), instance_(instance) {

    }

    jsi::Object getProtocolConfig(jsi::Runtime &rt) override {
      static_assert(
          bridging::getParameterCount(&T::getProtocolConfig) == 1,
          "Expected getProtocolConfig(...) to have 1 parameters");

      return bridging::callFromJs<jsi::Object>(
          rt, &T::getProtocolConfig, jsInvoker_, instance_);
    }
    double computeChunkSize(jsi::Runtime &rt, double mtuSize) override {
      static_assert(
          bridging::getParameterCount(&T::computeChunkSize) == 2,
          "Expected computeChunkSize(...) to have 2 parameters");

      return bridging::callFromJs<double>(
          rt, &T::computeChunkSize, jsInvoker_, instance_, std::move(mtuSize));
    }
    jsi::Object beginSession(jsi::Runtime &rt, jsi::String firmwarePath, jsi::String version, double mtuSize) override {
      static_assert(
          bridging::getParameterCount(&T::beginSession) == 4,
          "Expected beginSession(...) to have 4 parameters");

      return bridging::callFromJs<jsi::Object>(
          rt, &T::beginSession, jsInvoker_, instance_, std::move(firmwarePath), std::move(version), std::move(mtuSize));
    }
    double updateMtu(jsi::Runtime &rt, double mtuSize) override {
      static_assert(
          bridging::getParameterCount(&T::updateMtu) == 2,
          "Expected updateMtu(...) to have 2 parameters");

      return bridging::callFromJs<double>(
          rt, &T::updateMtu, jsInvoker_, instance_, std::move(mtuSize));
    }
    jsi::String buildStartCommand(jsi::Runtime &rt) override {
      static_assert(
          bridging::getParameterCount(&T::buildStartCommand) == 1,
          "Expected buildStartCommand(...) to have 1 parameters");

      return bridging::callFromJs<jsi::String>(
          rt, &T::buildStartCommand, jsInvoker_, instance_);
    }
    jsi::String buildFinishCommand(jsi::Runtime &rt) override {
      static_assert(
          bridging::getParameterCount(&T::buildFinishCommand) == 1,
          "Expected buildFinishCommand(...) to have 1 parameters");

      return bridging::callFromJs<jsi::String>(
          rt, &T::buildFinishCommand, jsInvoker_, instance_);
    }
    jsi::Object nextChunk(jsi::Runtime &rt) override {
      static_assert(
          bridging::getParameterCount(&T::nextChunk) == 1,
          "Expected nextChunk(...) to have 1 parameters");

      return bridging::callFromJs<jsi::Object>(
          rt, &T::nextChunk, jsInvoker_, instance_);
    }
    jsi::Object confirmChunkWritten(jsi::Runtime &rt, double byteLength) override {
      static_assert(
          bridging::getParameterCount(&T::confirmChunkWritten) == 2,
          "Expected confirmChunkWritten(...) to have 2 parameters");

      return bridging::callFromJs<jsi::Object>(
          rt, &T::confirmChunkWritten, jsInvoker_, instance_, std::move(byteLength));
    }
    jsi::Object rewindToStart(jsi::Runtime &rt) override {
      static_assert(
          bridging::getParameterCount(&T::rewindToStart) == 1,
          "Expected rewindToStart(...) to have 1 parameters");

      return bridging::callFromJs<jsi::Object>(
          rt, &T::rewindToStart, jsInvoker_, instance_);
    }
    jsi::Object parseStatus(jsi::Runtime &rt, jsi::String statusBase64) override {
      static_assert(
          bridging::getParameterCount(&T::parseStatus) == 2,
          "Expected parseStatus(...) to have 2 parameters");

      return bridging::callFromJs<jsi::Object>(
          rt, &T::parseStatus, jsInvoker_, instance_, std::move(statusBase64));
    }
    jsi::Object applyStatus(jsi::Runtime &rt, jsi::String statusBase64) override {
      static_assert(
          bridging::getParameterCount(&T::applyStatus) == 2,
          "Expected applyStatus(...) to have 2 parameters");

      return bridging::callFromJs<jsi::Object>(
          rt, &T::applyStatus, jsInvoker_, instance_, std::move(statusBase64));
    }
    jsi::Object getProgress(jsi::Runtime &rt) override {
      static_assert(
          bridging::getParameterCount(&T::getProgress) == 1,
          "Expected getProgress(...) to have 1 parameters");

      return bridging::callFromJs<jsi::Object>(
          rt, &T::getProgress, jsInvoker_, instance_);
    }
    bool isTransferComplete(jsi::Runtime &rt) override {
      static_assert(
          bridging::getParameterCount(&T::isTransferComplete) == 1,
          "Expected isTransferComplete(...) to have 1 parameters");

      return bridging::callFromJs<bool>(
          rt, &T::isTransferComplete, jsInvoker_, instance_);
    }
    bool isFlashConfirmed(jsi::Runtime &rt) override {
      static_assert(
          bridging::getParameterCount(&T::isFlashConfirmed) == 1,
          "Expected isFlashConfirmed(...) to have 1 parameters");

      return bridging::callFromJs<bool>(
          rt, &T::isFlashConfirmed, jsInvoker_, instance_);
    }
    void abortSession(jsi::Runtime &rt) override {
      static_assert(
          bridging::getParameterCount(&T::abortSession) == 1,
          "Expected abortSession(...) to have 1 parameters");

      return bridging::callFromJs<void>(
          rt, &T::abortSession, jsInvoker_, instance_);
    }

  private:
    friend class NativeLibOTAModuleCxxSpec;
    T *instance_;
  };

  Delegate delegate_;
};

} // namespace facebook::react
