module.exports = {
  root: true,
  ignorePatterns: ['**/node_modules/**', '**/dist/**', '**/*.d.ts'],
  env: {
    browser: true,
    node: true,
    commonjs: true,
    es6: true,
    jest: true,
    mocha: true,
    es2017: true,
    es2020: true,
    worker: true,
  },
  parserOptions: {
    ecmaVersion: 11,
    sourceType: 'module',
    ecmaFeatures: {
      jsx: true,
      legacyDecorators: true,
    },
  },
  rules: {
    'prefer-const': 'warn',
    'object-shorthand': 'warn',
    'no-empty-pattern': 'warn',
    'no-unused-vars': [
      'warn',
      { args: 'none', varsIgnorePattern: 'React', argsIgnorePattern: '^_' },
    ],
    'no-extra-boolean-cast': ['warn', { enforceForLogicalOperands: true }],
    'no-empty-function': 'warn',
    'no-implicit-coercion': ['warn', { allow: ['!!', '~'] }],
    'no-empty': 'warn',
    'dot-notation': 'warn',
    'no-unneeded-ternary': 'warn',
    'import/no-duplicates': 'warn',
    'no-undef-init': 'warn',
    'no-unreachable': 'warn',
    'no-useless-constructor': 'warn',

    'no-inner-declarations': ['error', 'both'],
    'no-self-assign': 'error',
    'no-sparse-arrays': 'error',
    'no-unsafe-optional-chaining': 'error',
    'constructor-super': 'error',
    'no-this-before-super': 'error',
    'no-undef': 'error',
    'getter-return': ['error', { allowImplicit: true }],
    'no-setter-return': 'error',
    'no-class-assign': 'error',
    'no-async-promise-executor': 'error',
    'no-func-assign': 'error',
    'no-unsafe-negation': 'error',
    'valid-typeof': 'error',
    'no-prototype-builtins': 'error',
    'use-isnan': 'error',
    'no-loss-of-precision': 'error',
    'for-direction': 'error',
    'no-ex-assign': 'error',
    'no-fallthrough': 'error',
    'no-unsafe-finally': 'error',
    'no-cond-assign': ['error', 'always'],
    'no-constant-condition': ['error', { checkLoops: false }],
    'no-compare-neg-zero': 'error',
    'no-invalid-regexp': 'error',
    'no-control-regex': 'error',
    'no-empty-character-class': 'error',
    'no-new-symbol': 'error',
    'no-with': 'error',
    'no-global-assign': 'error',
    'no-debugger': 'error',
    'no-dupe-class-members': 'error',
    'no-dupe-else-if': 'error',
    'no-duplicate-case': 'error',
    'no-import-assign': 'error',
    'no-obj-calls': 'error',
    'no-useless-catch': 'error',

    'no-var': 'error',
    'no-new-object': 'error',
    'no-array-constructor': 'error',
    'prefer-promise-reject-errors': 'error',
    'no-extra-bind': 'error',
    'prefer-template': 'warn',
    'no-multi-str': 'error',
    'guard-for-in': 'warn',
    'default-case': 'error',
    'default-case-last': 'error',
    'no-unmodified-loop-condition': 'error',
    eqeqeq: 'error',
    'no-eval': 'error',
    'no-new-wrappers': 'error',
    'no-caller': 'error',
    'no-implied-eval': 'error',
    'no-throw-literal': 'error',
  },
  plugins: ['@babel', 'import', 'lodash', 'eslint-plugin-promise', 'jest'],
  overrides: [
    {
      files: ['**/*.d.ts'],
      rules: {
        'spaced-comment': 'off',
      },
    },
    {
      files: ['**/*.js', '**/*.mjs', '**/*.cjs', '**/*.jsx'],
      parser: '@babel/eslint-parser',
      parserOptions: {
        ecmaVersion: 11,
        sourceType: 'module',
        ecmaFeatures: {
          jsx: true,
          legacyDecorators: true,
        },
        requireConfigFile: false,
        babelOptions: {
          configFile: false,
          plugins: [],
        },
      },
    },
    {
      files: ['**/*.ts', '**/*.tsx'],
      parser: '@typescript-eslint/parser',
      plugins: ['@typescript-eslint/eslint-plugin'],
      rules: {
        'no-undef': 'off',
        'no-redeclare': 'off',
        'no-implied-eval': 'off',
        'no-array-constructor': 'off',
        'no-loss-of-precision': 'off',
        'no-empty-function': 'off',
        'no-unused-vars': 'off',
        'default-param-last': 'off',
        'no-dupe-class-members': 'off',
        'only-throw-error': 'off',
        'no-useless-constructor': 'off',
        'dot-notation': 'off',

        strict: ['error', 'never'],

        '@typescript-eslint/consistent-type-assertions': [
          'warn',
          { assertionStyle: 'as', objectLiteralTypeAssertions: 'allow-as-parameter' },
        ],
        '@typescript-eslint/consistent-type-exports': ['error'],
        '@typescript-eslint/consistent-type-imports': ['warn'],
        '@typescript-eslint/no-unnecessary-boolean-literal-compare': 'warn',
        '@typescript-eslint/prefer-optional-chain': 'warn',
        '@typescript-eslint/no-empty-function': 'warn',
        '@typescript-eslint/no-empty-interface': 'warn',
        '@typescript-eslint/no-duplicate-enum-values': 'warn',
        '@typescript-eslint/no-useless-constructor': 'warn',
        '@typescript-eslint/no-require-imports': 'warn',
        '@typescript-eslint/unified-signatures': 'warn',
        '@typescript-eslint/method-signature-style': 'warn',
        '@typescript-eslint/no-var-requires': 'warn',
        '@typescript-eslint/no-non-null-asserted-optional-chain': 'warn',
        '@typescript-eslint/no-namespace': [
          'warn',
          {
            // Discourage "namespace" in .ts and .tsx files
            allowDeclarations: false,

            // Allow it in .d.ts files that describe legacy libraries
            allowDefinitionFiles: false,
          },
        ],
        '@typescript-eslint/no-redundant-type-constituents': 'warn',

        '@typescript-eslint/no-misused-new': 'error',
        '@typescript-eslint/no-array-constructor': 'error',
        '@typescript-eslint/no-non-null-assertion': 'warn',
        '@typescript-eslint/no-extra-non-null-assertion': 'error',
        '@typescript-eslint/adjacent-overload-signatures': 'error',
        '@typescript-eslint/no-this-alias': 'error',
        '@typescript-eslint/no-explicit-any': 'warn',
        '@typescript-eslint/no-unnecessary-type-constraint': 'error',
        '@typescript-eslint/no-loss-of-precision': 'error',
        '@typescript-eslint/no-unused-vars': ['warn', { args: 'none', argsIgnorePattern: '^_' }],
        '@typescript-eslint/prefer-as-const': 'error',
        '@typescript-eslint/prefer-namespace-keyword': 'error',

        '@typescript-eslint/no-implied-eval': 'error',

        '@typescript-eslint/only-throw-error': 'error',
        '@typescript-eslint/no-non-null-asserted-nullish-coalescing': 'error',
        '@typescript-eslint/prefer-literal-enum-member': 'error',

        '@typescript-eslint/no-dupe-class-members': 'error',
        'import/order': [
          'warn',
          {
            alphabetize: {
              caseInsensitive: true,
              order: 'asc',
            },
            groups: ['builtin', 'external', 'internal', 'parent', 'sibling', 'index', 'object'],
            'newlines-between': 'always',
            pathGroups: [
              {
                pattern: '@/**',
                group: 'internal',
                position: 'before',
              },
            ],
            pathGroupsExcludedImportTypes: ['builtin'],
          },
        ],
        'sort-imports': [
          'warn',
          {
            ignoreDeclarationSort: true,
          },
        ],
      },
    },
    {
      files: ['*.{spec,test}.{js,ts,tsx}', '**/__{mocks,tests}__/**/*.{js,ts,tsx}'],
      env: {
        jest: true,
      },
      rules: {
        'react-native/no-inline-styles': 0,
        quotes: [1, 'single', { avoidEscape: true, allowTemplateLiterals: true }],
      },
    },
  ],
};
