/**
 * Android JNI module-provider declaration for the RTNLibGP codegen library.
 *
 * React Native's C++ autolinking (autolinking.cpp) unconditionally emits
 *   #include <RTNLibGP.h>
 * and a call to `RTNLibGP_ModuleProvider(...)` for any dependency that exposes
 * a codegen `libraryName`. For a normal Java/Kotlin Turbo Module this header is
 * generated by codegen and returns a JavaTurboModule. RTNLibGP is a *pure C++*
 * Turbo Native Module, so the provider declines (returns nullptr) and the
 * module is instead supplied by the C++ provider (autolinking_cxxModuleProvider
 * -> NativeLibGPModule).
 *
 * This file is Android-only (it depends on the JNI
 * <ReactCommon/JavaTurboModule.h>) and therefore lives outside cpp/_generated,
 * which is shared with iOS.
 */

#pragma once

#include <ReactCommon/JavaTurboModule.h>
#include <ReactCommon/TurboModule.h>

#include <memory>
#include <string>

namespace facebook::react {

std::shared_ptr<TurboModule> RTNLibOTA_ModuleProvider(
    const std::string& moduleName, const JavaTurboModule::InitParams& params);

}  // namespace facebook::react
